### ISSUE TITLE
GUI issue in Windows 10

### ISSUE THREAD

**Issue by Tom-2266** [cortex-lab/phy#946] opened 2020-01-28 10:15 UTC
I am having a problem trying to open a data set. The interface opens with huge font and is basically unusable. See attached picture:
![image](https://user-images.githubusercontent.com/60385600/73254493-6dc98c80-41b6-11ea-9131-1b830d8a0dea.png)

I have seen that other people have had the same problem but I have been unable to fix it. The graphics card I have is Intel UHD Graphics 630. I have tried updating drivers and rolling back to previous driver versions. I don't have a dedicated graphics card. 
Any help would be very much appreciated

**Comment by rossant** [comment] 2020-01-28 12:18
Unfortunately I don't know how to fix this without a non-intel graphics chipset, and I'm unable to reproduce this at the moment.

It might be helpful if you could try to close all views in the GUI, and see if you still have this problem with just 1 or 2 views open.

**Comment by Tom-2266** [comment] 2020-02-06 15:43
Hi, sorry for the long reply.
I can close views and move them around outside the template GUI window and they look fine
I can also add some views to the template GUI window and it seems to work
![image](https://user-images.githubusercontent.com/60385600/73952038-6e6ccc00-48f6-11ea-879b-cbb4e7166d02.png)

But if i try to add in the cluster view or similarity view it completely messes up the whole display
![image](https://user-images.githubusercontent.com/60385600/73952395-c0aded00-48f6-11ea-8aa8-719b7222621e.png)
 
So it seems to be an issue with those two views. Strangely they both seem to work well on their own or together but the problems arise when adding in another view

**Comment by rossant** [comment] 2020-02-06 19:58
Thanks, that was helpful. I'll try to tackle this after the next release.

**Comment by rossant** [comment] 2020-02-07 11:28
Closing, discussion now on https://github.com/cortex-lab/phy/issues/951

**Closed by rossant** 2020-02-07 11:28 UTC
Labels: bug
