### ISSUE TITLE
Clusterview column labels 

### ISSUE THREAD

**Issue by noamroth** [cortex-lab/phy#1008] opened 2020-05-18 17:46 UTC
Hi,
I'm wondering if there is a way to keep the clusterview column labels visible while scrolling down to look through different clusters. As it currently is, when you scroll down, the column labels disappear, so it is hard to know what label each column of values corresponds to. 
Thanks!

**Comment by rossant** [comment] 2020-06-08 09:57
Yes, this will likely require #951

**Comment by rossant** [comment] 2020-06-08 10:21
duplicate of #1013

**Closed by rossant** 2020-06-08 10:21 UTC
Labels: enhancement
