### ISSUE TITLE
Mac OS Mojave javascript error for Table

### ISSUE THREAD

**Issue by carsen-stringer** [cortex-lab/phy#878] opened 2019-08-22 21:41 UTC
Phy starts but the views are all wrong and this error pops up in a dialog:

`
[JS:L1629] Uncaught ReferenceError: Table is not defined
`

Btw this was done in a (phy2) environment created with the instructions from the ReadTheDocs

**Comment by rossant** [comment] 2019-08-23 12:04
Thanks, closing as duplicate of #874, I'll test on a mac and report back

**Closed by rossant** 2019-08-23 12:04 UTC
Labels: bug
