### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by miguelconcham** [cortex-lab/phy#1268] opened 2024-04-09 13:10 UTC
Hi,

I started getting this error message when trying to run Phy. I understand now that this seems to be a Python version problem (even though I don't remember updating Python so far). Any clue where the problem is coming from?

Thanks for your help!

Miguel

**Comment by zm711** [comment] 2024-04-12 18:24
Yeah there is no limit set in the environment.yml. So it will install latest python unless you specify 3.11 or below. So if installing with the yml just edit the line that says 
```
python
```
 to 
```
python=3.11
```

**Comment by mtehrani-code** [comment] 2024-04-29 20:32
@zm711 I'm having the same issue now installing phy2. I created the environment:

**Comment by zm711** [comment] 2024-04-29 21:24
@mtehrani-code could you type `conda list` and post that here.

**Comment by zm711** [comment] 2024-04-30 15:11
@mtehrani-code I would need it from your Phy environment. If you look at this list you don't have phy installed in this environment. 

You would need to do
```bash
conda activate phy2
conda list
```

So we can see in there. Phy usually goes into its own private environment.

**Comment by mtehrani-code** [comment] 2024-04-30 15:14
Of course! Here it is:

abseil-cpp                20211102.0           hd77b12b_0
arrow-cpp                 14.0.2               ha81ea56_1
asttokens                 2.0.5              pyhd3eb1b0_0
aws-c-auth                0.6.19               h2bbff1b_0
aws-c-cal                 0.5.20               h2bbff1b_0
aws-c-common              0.8.5                h2bbff1b_0
aws-c-compression         0.2.16               h2bbff1b_0
aws-c-event-stream        0.2.15               hd77b12b_0
aws-c-http                0.6.25               h2bbff1b_0
aws-c-io                  0.13.10              h2bbff1b_0
aws-c-mqtt                0.7.13               h2bbff1b_0
aws-c-s3                  0.1.51               h2bbff1b_0
aws-c-sdkutils            0.1.6                h2bbff1b_0
aws-checksums             0.1.13               h2bbff1b_0
aws-crt-cpp               0.18.16              hd77b12b_0
aws-sdk-cpp               1.10.55              hd77b12b_0
blas                      1.0                         mkl
bokeh                     3.4.0           py312hfc267ef_1
boost-cpp                 1.82.0               h59b6b97_2
bottleneck                1.3.7           py312he558020_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotli-python             1.0.9           py312hd77b12b_7
bzip2                     1.0.8                h2bbff1b_5
c-ares                    1.19.1               h2bbff1b_0
ca-certificates           2024.3.11            haa95532_0
certifi                   2024.2.2        py312haa95532_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.7           py312haa95532_0
cloudpickle               2.2.1           py312haa95532_0
colorama                  0.4.6           py312haa95532_0
colorcet                  3.1.0                    pypi_0    pypi
comm                      0.2.1           py312haa95532_0
contourpy                 1.2.0           py312h59b6b97_0
cycler                    0.11.0             pyhd3eb1b0_0
cython                    3.0.10          py312h2bbff1b_0
cytoolz                   0.12.2          py312h2bbff1b_0
dask                      2023.11.0       py312haa95532_0
dask-core                 2023.11.0       py312haa95532_0
debugpy                   1.6.7           py312hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
distributed               2023.11.0       py312haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.6.2                hd77b12b_0
fonttools                 4.51.0          py312h2bbff1b_0
freetype                  2.12.1               ha860e81_0
fsspec                    2023.10.0       py312haa95532_0
gflags                    2.2.2                hd77b12b_1
ghp-import                2.1.0                    pypi_0    pypi
glog                      0.5.0                hd77b12b_1
grpc-cpp                  1.48.2               hfe90ff0_1
h5py                      3.9.0           py312h59a1360_0
hdf5                      1.12.1               h51c971a_3
heapdict                  1.0.1              pyhd3eb1b0_0
icc_rt                    2022.1.0             h6049295_2
icu                       73.1                 h6c2663c_0
idna                      3.7             py312haa95532_0
importlib-metadata        7.0.1           py312haa95532_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2023.1.0         h59b6b97_46320
ipykernel                 6.28.0          py312haa95532_0
ipython                   8.20.0          py312haa95532_0
jedi                      0.18.1          py312haa95532_1
jinja2                    3.1.3           py312haa95532_0
joblib                    1.4.0           py312haa95532_0
jpeg                      9e                   h2bbff1b_1
jupyter_client            8.6.0           py312haa95532_0
jupyter_core              5.5.0           py312haa95532_0
kiwisolver                1.4.4           py312hd77b12b_0
krb5                      1.20.1               h5b6d351_0
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libboost                  1.82.0               h3399ecb_2
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  14.0.6          default_hb5a9fac_1
libclang13                14.0.6          default_h8e68704_1
libcurl                   8.5.0                h86230a5_0
libdeflate                1.17                 h2bbff1b_1
libevent                  2.1.12               h56d1f94_1
libffi                    3.4.4                hd77b12b_0
libpng                    1.6.39               h8cc25b3_0
libpq                     12.17                h906ac69_0
libprotobuf               3.20.3               h23ce68f_0
libsodium                 1.0.18               h62dcd97_0
libssh2                   1.10.0               he2ea4bf_2
libthrift                 0.15.0               h4364b78_2
libtiff                   4.5.1                hd77b12b_0
libwebp-base              1.3.2                h2bbff1b_0
locket                    1.0.0           py312haa95532_0
lz4                       4.3.2           py312h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.6                      pypi_0    pypi
markupsafe                2.1.3           py312h2bbff1b_0
matplotlib                3.8.4           py312haa95532_0
matplotlib-base           3.8.4           py312hc7c4135_0
matplotlib-inline         0.1.6           py312haa95532_0
mergedeep                 1.3.4                    pypi_0    pypi
mkdocs                    1.6.0                    pypi_0    pypi
mkdocs-get-deps           0.2.0                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0           py312h2bbff1b_1
mkl_fft                   1.3.8           py312h2bbff1b_0
mkl_random                1.2.4           py312h59b6b97_0
msgpack-python            1.0.3           py312h59b6b97_0
mtscomp                   1.0.2                    pypi_0    pypi
nest-asyncio              1.6.0           py312haa95532_0
numexpr                   2.8.7           py312h96b7d27_0
numpy                     1.26.4          py312hfd52020_0
numpy-base                1.26.4          py312h4dde369_0
openjpeg                  2.4.0                h4fc8c34_0
openssl                   3.0.13               h2bbff1b_0
orc                       1.7.4                h623e30f_1
packaging                 23.2            py312haa95532_0
pandas                    2.2.1           py312h0158946_0
parso                     0.8.3              pyhd3eb1b0_0
partd                     1.4.1           py312haa95532_0
pathspec                  0.12.1                   pypi_0    pypi
phy                       2.0b5                    pypi_0    pypi
phylib                    2.4.3                    pypi_0    pypi
pillow                    10.3.0          py312h2bbff1b_0
pip                       23.3.1          py312haa95532_0
platformdirs              3.10.0          py312haa95532_0
pluggy                    1.0.0           py312haa95532_1
ply                       3.11            py312haa95532_1
prompt-toolkit            3.0.43          py312haa95532_0
prompt_toolkit            3.0.43               hd3eb1b0_0
psutil                    5.9.0           py312h2bbff1b_0
pure_eval                 0.2.2              pyhd3eb1b0_0
pyarrow                   14.0.2          py312had8a6e9_0
pybind11-abi              5                    hd3eb1b0_0
pygments                  2.15.1          py312haa95532_1
pyopengl                  3.1.1a1         py312haa95532_0
pyparsing                 3.0.9           py312haa95532_0
pyqt                      5.15.10         py312hd77b12b_0
pyqt5-sip                 12.13.0         py312h2bbff1b_0
pyqtwebengine             5.15.10         py312hd77b12b_0
pysocks                   1.7.1           py312haa95532_0
pytest                    7.4.0           py312haa95532_0
python                    3.12.3               h1d929f7_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-lmdb               1.4.1           py312hd77b12b_0
python-tzdata             2023.3             pyhd3eb1b0_0
pytz                      2024.1          py312haa95532_0
pywin32                   305             py312h2bbff1b_0
pyyaml                    6.0.1           py312h2bbff1b_0
pyyaml-env-tag            0.1                      pypi_0    pypi
pyzmq                     25.1.2          py312hd77b12b_0
qt-main                   5.15.2              h19c9488_10
qt-webengine              5.15.9               h5bd16bc_7
qtconsole                 5.5.1           py312haa95532_0
qtpy                      2.4.1           py312haa95532_0
re2                       2022.04.01           hd77b12b_0
requests                  2.31.0          py312haa95532_1
responses                 0.25.0          py312haa95532_0
scikit-learn              1.4.2           py312hc7c4135_1
scipy                     1.13.0          py312hbb039d4_0
setuptools                68.2.2          py312haa95532_0
sip                       6.7.12          py312hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.10               h6c2663c_1
sortedcontainers          2.4.0              pyhd3eb1b0_0
sqlite                    3.41.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
tbb                       2021.8.0             h59b6b97_0
tblib                     1.7.0              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.12               h2bbff1b_0
toolz                     0.12.0          py312haa95532_0
tornado                   6.3.3           py312h2bbff1b_0
tqdm                      4.66.2                   pypi_0    pypi
traitlets                 5.7.1           py312haa95532_0
tzdata                    2024a                h04d1e81_0
unicodedata2              15.1.0          py312h2bbff1b_0
urllib3                   2.1.0           py312haa95532_1
utf8proc                  2.6.1                h2bbff1b_1
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  4.0.0                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0
wheel                     0.41.2          py312haa95532_0
win_inet_pton             1.1.0           py312haa95532_0
xyzservices               2022.9.0        py312haa95532_1
xz                        5.4.6                h8cc25b3_0
yaml                      0.2.5                he774522_0
zeromq                    4.3.5                hd77b12b_0
zict                      3.0.0           py312haa95532_0
zipp                      3.17.0          py312haa95532_0
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0

**Comment by zm711** [comment] 2024-04-30 15:17
@mtehrani-code 

The problem is this line
```
python 3.12.3 h1d929f7_0
```

You've installed python 3.12 into the Phy environment. and Phy is only compatible with python < 3.12.

You need to use the `environment.yaml` then you need to open it and edit the python line and switch it to:

python=3.11

before you make the environment.

**Comment by mtehrani-code** [comment] 2024-04-30 20:43
@zm711 This is the first step listed for installing phy:

**Create a new conda environment** with the conda dependencies:

conda create -n phy2 -y cython dask h5py joblib matplotlib numpy pillow pip pyopengl pyqt pyqtwebengine pytest python qtconsole requests responses scikit-learn scipy traitlets

If I need to change python 3.12 to 3.11 in the environment.yaml file _before_ creating the environment, then where is this file coming from? (sorry, if I'm missing something obvious) 

...I couldn't locate an environment.yaml file. So I did some googling and tried this instead:

(phy2) C:\Users\matta>conda env export > environment.yml 

Then I typed:
(phy2) C:\Users\matta>environment.yml

Then opened this file in notepad, and changed python 3.12 to 3.11 and saved.

Then typed:

(phy2) C:\Users\matta>conda env update --file environment.yml --prune

And got this message:

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python==3.11.3=h1d929f7_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

Sorry a bit lost here.

**Comment by zm711** [comment] 2024-04-30 20:51
Yeah @mtehrani-code, unfortunately this repo isn't quite as actively maintained any more. I just hop on to help people with installation instructions. Basically the instructions you followed are wrong now for a couple reasons (python 3.12 being one problem and the `requirements.txt` being another). 

```yaml
name: phy2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - git
  - numpy
  - matplotlib
  - scipy
  - h5py
  - pyqt
  - pyopengl
  - pyqtwebengine
  - pytest
  - qtconsole
  - requests
  - responses
  - traitlets
  - dask
  - cython
  - pillow
  - scikit-learn
  - joblib
  - pip:
    - git+https://github.com/cortex-lab/phy.git
 ```

You can just copy these packages into a text editor and then save it as a yml file. Then what we should do it cleanup the broken install. I'm just going to give you the more extreme option since you are bit newer to this.

first we will do

```bash
conda remove -n phy2 --all
```

then we will install with our environment.yaml

```bash
conda env create -f environment.yaml
```

Now for this to work you'll need to be in the correct folder so if you save it in documents you need to first go to documents

```bash
cd documents
conda env create -f enviroment.yaml
```

The other pitfall is that you could accidentally give it the `yml` instead of `yaml` suffix so if the above command fails and you're in the right folder do

```bash
conda env create -f environment.yml
```

**Comment by mtehrani-code** [comment] 2024-05-29 21:28
@zm711 Hi Zach!

I'm picking the Phy installation back up and still having issues with it.

I did downgrade to python 3.9 and that seems to take care of the 'imp not found' error.

However, now when I type in phy template-gui params.py I get this error message:

ImportError: DLL load failed while importing _imaging: The specified module could not be found.

Could you please advise?

Here is the full message:

(phy2) C:\Users\matta\Documents\Kilosort-2.5>phy template-gui params.py
Traceback (most recent call last):
  File "C:\Users\matta\anaconda3\envs\phy2\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\matta\anaconda3\envs\phy2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\matta\anaconda3\envs\phy2\Scripts\phy.exe\__main__.py", line 4, in <module>
  File "C:\Users\matta\anaconda3\envs\phy2\lib\site-packages\phy\__init__.py", line 21, in <module>
    from .utils.config import load_master_config
  File "C:\Users\matta\anaconda3\envs\phy2\lib\site-packages\phy\utils\__init__.py", line 11, in <module>
    from .color import(
  File "C:\Users\matta\anaconda3\envs\phy2\lib\site-packages\phy\utils\color.py", line 17, in <module>
    from matplotlib.colors import hsv_to_rgb, rgb_to_hsv
  File "C:\Users\matta\anaconda3\envs\phy2\lib\site-packages\matplotlib\__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\matta\anaconda3\envs\phy2\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\matta\anaconda3\envs\phy2\lib\site-packages\matplotlib\colors.py", line 52, in <module>
    from PIL import Image
  File "C:\Users\matta\anaconda3\envs\phy2\lib\site-packages\PIL\Image.py", line 88, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

**Comment by zm711** [comment] 2024-06-07 12:11
Howdy @mtehrani-code,

Did this ever work?

**Comment by mtehrani-code** [comment] 2024-06-07 15:34
Hi Zach!

Yes, I got help from someone who is experienced with this. In addition to downgrading python, apparently I also needed to install a number of modules in specific versions. I'm putting them here for anyone else who might run into the same issue. This seemed to take care of the 'imp' error...

conda install aws-c-common=0.9.18 \
aws-crt-cpp=0.26.8 \
ca-certificates=2024.2.2 \
certifi=2024.2.2 \
cython=3.0.10 \
debugpy=1.8.1 \
fonttools=4.51.0 \
h5py=3.11.0 \
hdf5=1.14.3 \
intel-openmp=2024.1.0 \
ipython=8.12.0 \
jupyter_core=5.7.2 \
libarrow=16.1.0 \
libclang13=18.1.5 \
libparquet=16.1.0 \
matplotlib=3.8.4 \
mkl=2024.1.0 \
numpy=1.26.4 \
pandas=2.2.2 \
pillow=10.3.0 \
pyarrow=16.1.0 \
pyqt=5.15.9 \
qt-main=5.15.8 \
scikit-learn=1.5.0 \
scipy=1.13.1 \
tornado=6.4

**Comment by zm711** [comment] 2024-06-07 17:47
Cool @mtehrani-code. I fixed the imp issue here, but great that it is working!

**Closed by zm711** 2024-06-07 17:47 UTC
