### ISSUE TITLE
hidden waveform views?

### ISSUE THREAD

**Issue by haiderlab** [cortex-lab/phy#849] opened 2019-07-02 22:27 UTC
hello phy team,

since the phy update from dev version, i often can't draw into or raise the default WaveformView.  Adding new WaveformViews (2), (3), etc. sometimes alleviates this, but keyboard shortcuts (overlap, toggle mean) then don't work and 'assertion errors' become common when running the wizard from these additional WaveformViews while interacting in other views (Raster, Feature).  This is only solved by killing all views except the ClusterView, and restarting. 

is there a simple way to reset to defaults / kill waveform views, so that the default view is drawn into / visible?

thanks

**Comment by rossant** [comment] 2019-07-03 07:01
Is this still happening on the very latest version on the dev branch?

**Comment by haiderlab** [comment] 2019-07-03 15:09
Yes, it is happening on the latest version

**Comment by rossant** [comment] 2019-07-03 15:24
Is this a duplicate of https://github.com/cortex-lab/phy/issues/848 ?
What is your OS?

**Comment by haiderlab** [comment] 2019-07-03 15:53
Windows 10.  Different from #848, and I haven't yet seen the same error described there.  I tried pip install PyQtWebEngine and this hasn't changed the behavior.  The same has just happened to the original FeatureView, I can no longer see it , select it, or maximize it...

**Comment by haiderlab** [comment] 2019-07-03 17:57
Posted a few screencaps here if helpful:
https://www.dropbox.com/sh/9ye71hzelopmisz/AAAWZZy0MhdU0R1kMdAzV9dja?dl=0

Image descriptions:
(1) Default view upon launching phy.  Menu shows WaveformView, and additional Views (2) and (3).  None of these are visible.  Also note that a cluster is selected and drawn into Feature View.  Launching wizard shows blue and next best red cluster in Feature view, but no WaveformViews.
(2) Addition of new WaveformView (3), visible at bottom.
(3) Docked WaveFormView(3) now shows clusters, but keyboard shortcuts are not active.  Toggling from dropdown menu works for a while, but eventually throw an AssertionError as described above, and windows hang / crash.
(4) Screencap from just two days ago with everything in working order (all default views, no additional views).  One thing that is different is that the file path is visible in the TemplateGUI menu bar at top left.

**Comment by rossant** [comment] 2019-07-03 18:39
Okay thanks, could you delete `~/.phy/TemplateGUI/state.json` to reset the window layout and try again?

**Comment by haiderlab** [comment] 2019-07-03 19:22
this appears to have solved the issue, thank you!

**Comment by rossant** [comment] 2019-07-05 13:58
Added a `--clear-config` option to the `phy` command to delete the global and local `state.json` and reset the GUI layout on startup.

**Closed by rossant** 2019-07-05 13:58 UTC
Labels: bug

**Comment by ijunhyuk** [comment] 2024-03-22 23:48
As of 2024 (phy version 2.0b5), I have resolved this issue with the following command. This command initialized the arrangement of View panels.

phy template-gui  params.py --clear-state
